### ISSUE TITLE
Complete test coverage

### ISSUE THREAD

**Issue by sb8244** [codeforatlanta/courtbot#1]
- [x] web.js tested
- [x] utils/loaddata.js
- [x] sendQueued.js
- [x] sendReminders.js
- [N] db.js (tested through other tests)

**Comment by sb8244** [comment]
@luigi a good chunk of this is in master now. Web.js had the most complicated HTTP endpoints, but the most complicated logic / testing path will be in the send\* files.

**Comment by luigi** [comment]
:+1:

**Comment by getabetterpic** [comment]
@sb8244 I've started work on the test for sendReminders.

**Comment by sb8244** [comment]
Bam. Thanks @getabetterpic
